### ISSUE TITLE
How to re-add the Show Frame Props button

### ISSUE THREAD

**Issue by shssoichiro** [Irrational-Encoding-Wizardry/vs-preview#104]
Since this feature was moved to a plugin, the Show Frame Props button which used to exist on the main toolbar has been missing. I've even tried manually adding it as a plugin but since I get "Tried to register plugin "Frame Props (dev.setsugen.frame_props)" twice!", I'm assuming it's supposed to be loaded by default without any extra work. I've checked all the sub-menus as well and can't find the button anymore.

![image](https://github.com/Irrational-Encoding-Wizardry/vs-preview/assets/5951392/55ddee46-0584-4e96-b5d9-45b7fcdf6fd0)

**Comment by Setsugennoao** [comment]
Yeah... because it's a plugin

**Comment by shssoichiro** [comment]
You didn't answer the question at all. Sorry that I'm apparently a dumbass, but there's no documentation on how to enable plugins in this software.

**Comment by Setsugennoao** [comment]
That wasn't your question. 
Anyways there's a draggable thing for the splitview at the right

**Comment by shssoichiro** [comment]
Oh, I see it now. So it was there the whole time, I just never thought to look there. Thanks.
