### ISSUE TITLE
Scroll through video nodes

### ISSUE THREAD

**Issue by McBaws** [Irrational-Encoding-Wizardry/vs-preview#105]
It would be nice to be able to just 'scroll' through all the video nodes with the up and down arrow keys, in addition to using the number keys. As it is now, it's super inconvenient to switch between nodes if you have more than 10.

Could also play in with #17, would be nice to have this as an option in a potential list of hotkeys.

**Comment by Setsugennoao** [comment]
what are you doing with more than 10 outputs bruh 💀

**Comment by Setsugennoao** [comment]
what about ALT + scrollwheel?

**Comment by McBaws** [comment]
Loaded every episode in one script on different nodes so I didn't have to keep reloading vspreview 💀
And yeah, any shortcut is fine as long as the feature is there ig.

**Comment by Setsugennoao** [comment]
💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀

**Comment by McBaws** [comment]
Ctrl+Tab and Ctrl+Shift+Tab fulfill this purpose, a hotkey explainer page would be helpful.
