### ISSUE TITLE
Previewing video results in completely wrong output

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-preview#115]
vspreview currently ignores clip frame props entirely, along with the heuristic check being seemingly nonfunctional, instead always assuming BT709 left-aligned chroma for everything. This obviously results in completely wrong output for a massive amount of sources.

**Comment by YomikoR** [comment]
Steps to reproduce?

**Comment by NSQY** [comment]
chromaloc issue seems to be valid, `TOP_LEFT` should be assumed for UHD.

**Comment by wiwaz** [comment]
> Steps to reproduce?

Just preview anything that is not BT.709 left chroma (i.e. 4K video)

**Comment by wiwaz** [comment]
In addition to the above, even if the heuristic check did work, it is not robudt enough and will fail on anything that is 4:3.
