### ISSUE TITLE
Add a resize calculator

### ISSUE THREAD

**Issue by Setsugennoao** [Irrational-Encoding-Wizardry/vs-preview#18]
Like the one from AVSpMod
![image](https://user-images.githubusercontent.com/41454651/172441209-82a3b239-477e-482c-9260-46852efdfeb8.png)

**Comment by LightArrowsEXE** [comment]
Should probably add a mode specifically designed for DVD cropping. Maybe make it a separate mode as well (like dft and descaling), where you can set the aspect ratio and try out different shifts, with a little balloon that explains what you should be looking for. I think that would drastically reduce the amount of poorly stretched DVD encodes around.

**Comment by Setsugennoao** [comment]
Better solution is https://github.com/Irrational-Encoding-Wizardry/vs-scale/issues/75
