### ISSUE TITLE
Split plane mode

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#20]
I think it'd be useful to have the ability to switch to a mode that has a clip split into its individual planes. This allows users to more easily follow how their filtering is affecting for example the chroma planes. Right now the best way to do so is to just split and stack them yourself, a la `lvsfunc.stack_planes`. I think having this kind of behaviour built-in under perhaps the same dropdown menu as dft would be a nice addition.

**Comment by Setsugennoao** [comment]
Added in https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/ca023dd129055d403000506e41b323d33b1e971c
