### ISSUE TITLE
Improve window size/position

### ISSUE THREAD

**Issue by DonCanjas** [Irrational-Encoding-Wizardry/vs-preview#21]
vs-preview always opens in the same position, which has to be moved, resized or open in fullscreen mode. 
This can lead to having part of the window hidden. Adding a option to launch in fullscreen window mode to settings would be nice.
  
The first example is default vspreview. 
On the second, I relaunched vspreview after toggling some of the extra options. The window is too tall for my display so I am forced to resize manually or switch to fullscreen.

<img src=https://files.catbox.moe/z9ab3s.png width="800"/>   
<img src=https://files.catbox.moe/dvomx5.png width="800"/>

**Comment by Setsugennoao** [comment]
Shoul be resolved after [#5d04108](https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/5d04108c81b011cf1b1a89bdc2dc90350e9c9705), which was requested in #34.

**Comment by Setsugennoao** [comment]
Windows issue.
