### ISSUE TITLE
Pipette new colour formats

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#28]
It'd be neat if the pipette also displayed HTML colour codes and HSL values (like aegisub). A couple filters use the first (like TColorMask), and the latter may be useful for other applications and is common enough in a fansubber's life.

**Comment by Setsugennoao** [comment]
I believe the pipette already has a lot of stuff
Should we look into a select (RGB&YUV&RAW / HTML&HSL&[HWB or ASS]) or making it double height?

**Comment by LightArrowsEXE** [comment]
I believe there's still plenty of space to work with. Maybe see what happens?

**Comment by Setsugennoao** [comment]
Added in https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/137533f1497650d91a17e4c64bcb031d03c6e971
