### ISSUE TITLE
Zoom from storage not applied when initial run errors

### ISSUE THREAD

**Issue by po5** [Irrational-Encoding-Wizardry/vs-preview#31]
Saved zoom is broken when
- Saved zoom != 100%
- Initial script load gives an error
- Reload doesn't error
You end up with your saved zoom value selected but not applied, e.g. 200% displayed in dropdown but the video is actually 100% zoom

**Comment by Setsugennoao** [comment]
Eventually fixed but I don't remember the commit.
Reopen if the issue persists in your setup. I can't reproduce anymore.
