### ISSUE TITLE
Save window geometry in global instead of local storage

### ISSUE THREAD

**Issue by shssoichiro** [Irrational-Encoding-Wizardry/vs-preview#34]
This is potentially related to #21, but I wasn't sure how much it overlapped so decided to create a new issue.

I think the common workflow is that most people want to have their vspreview window in the same location for each video file they're working on, rather than having it reset to the default location for each new file. Having to move the window each time is a minor annoyance rather than a significant issue, but it would be more convenient, in my opinion, to have the geometry saved globally rather than per file.

**Comment by Setsugennoao** [comment]
Thanks for opening the issue.
I made the window settings (timeline, window geometry, window state) part of the global state in [#5d04108](https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/5d04108c81b011cf1b1a89bdc2dc90350e9c9705).

**Comment by shssoichiro** [comment]
It doesn't seem to be working correctly, for me at least. I see that the window settings are saved in the global config, but when I reopen vspreview, the window position is at the default. I'm using two monitors, in case this might have any effect on it?
