### ISSUE TITLE
Add more previewer dithering modes

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-preview#35]
Sometimes it may be desired to preview with ordered dithering, or even no dithering at all. An option to configure this with ease would be very convenient.

**Comment by Setsugennoao** [comment]
Should this be a global or local config?

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/a6a7d22f727afbd4afc7d2a67074d1a255011980
