### ISSUE TITLE
comp: n frames between frames settings

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#39]
With the current random implementation, you can sometimes get a lot of frames that are right next to each other. I think having a "`n` frames between comparison frames" option would help alleviate that issue somewhat. Otherwise, you could always add some kind of similarity check with the previous frame in the list, and maybe automatically ignore frames that are x% a solid colour. This will stop it from randomly picking fully white/black frames.

Ideally these would all be settings too, so people can use them if they want to, or otherwise just go full random.

**Comment by RainingTerror7** [comment]
bump

**Comment by Setsugennoao** [comment]
Moved to #89
