### ISSUE TITLE
Frame Props dialog shows BT.709 Primaries as Unspecified

### ISSUE THREAD

**Issue by shssoichiro** [Irrational-Encoding-Wizardry/vs-preview#41]
Gotta admit this is a weird one, because I checked the code and the primaries are indeed in the correct order in the list vspreview has.

The issue I'm seeing is that, when opening the Frame Props dialog for a script where `_Primaries` is set to `1`, the Frame Props dialog shows "Unspecified" instead of the expected "BT.709". Matrix and Transfer properties display correctly, and all other Primaries except BT.709 also display correctly.

**Comment by Setsugennoao** [comment]
I don't know what's up with the props lately, I also got people telling me that limited color range is displaywled as full.

I will fix all of these issues once I switch to the new package I,ve written, `vstools`, which has got all the enums needed and helper functions to get the values from frame props _prop_erly.

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/eafdde3a6d89f573c9485aced1f8f0b831f3e771
