### ISSUE TITLE
Comp prompt user when comparison is done

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#45]
Making comparisons, especially on filtered output, can take a while. If the user is using vspreview directly, it might be nice if the program on the taskbar flashes orange when the comparison is done. I'm not sure how feasible this is, but it should at least be possible on Windows. Maybe worth making a generic function in case you wanna start prompting users for other tasks, too?

**Comment by Setsugennoao** [comment]
It now gives full progress, on upload too. I don't think this is needed anymore

**Comment by LightArrowsEXE** [comment]
I agree.
