### ISSUE TITLE
Print comp progress to stdout

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#48]
Copied from #29.

Additional nicety would be to also print the progress of comps being made to stdout, including the final url. Useful in case you close vspreview but forgot to copy the link, or if it crashes straight after uploading (as has happened to me before).

**Comment by Setsugennoao** [comment]
vspreview now prints the url in a .url file so printing to console seems useless for the reason of crash/missing to copy it.
what would be the reason of printing the progress to console?

**Comment by LightArrowsEXE** [comment]
Late, but it'd be to allow users to easily follow progress without having to open the vspreview window. From time to time, if you've got some filtering going on on one of the output nodes, vspreview will just crash without any warnings if you tab back into it while it's trying to load frames. Printing the output to stdout, maybe with a fancy progress bar \*wink wink\* means the user only needs to open up their editor or terminal to see how far it has progressed.
