### ISSUE TITLE
Automatically resize frameprop text and/or window menu

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#59]
If your clip has a buttload of props, the frameprop menu will display them like this.

![image](https://user-images.githubusercontent.com/42927908/206858275-9be80244-94c1-4ab3-a994-fbbea0c285dd.png)

You won't often get *this* many props, but automatic scaling/windows resizing to accommodate all of them (maybe with a max height of the user's screen height or something to avoid it getting waaaayy too long?) would be appreciated.

**Comment by NSQY** [comment]
>You won't often get this many props

If you're dealing with PQ sources that contain mastering information, it won't be so uncommon as you've got an 8 or 9 props to deal with by default.

![props](https://user-images.githubusercontent.com/34185288/206887853-bdf94cff-fd1a-4991-8a1a-307b77841708.png)

**Comment by Setsugennoao** [comment]
The fix would be rendering a scrollable item, but I'm concerned with speed in playback.
