### ISSUE TITLE
Video is always scaled when Windows DPI scaling is enabled

### ISSUE THREAD

**Issue by dixie-flatliner** [Irrational-Encoding-Wizardry/vs-preview#61]
Per the title, I've noticed that in recent versions (using latest version from PyPi as of 12/28, about 10 minutes ago), vspreview's video output* is now automatically scaled when Windows DPI scaling is enabled, and I can't find a way to disable it (I have fiddled with the DPI option in settings, too, to no effect). This means that unless I disable DPI scaling in Windows, I can't view my filterchain without vspreview's scaling. A workaround would be greatly appreciated.

** Edit: I'm dumb, setting a custom zoom level allows bypassing this. Just assumed it'd be upscaled and then downscaled.

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/be2a8312d33ba360b9ad8704e1cb98a260763efb.
