### ISSUE TITLE
High DPI rendering

### ISSUE THREAD

**Issue by dtlnor** [Irrational-Encoding-Wizardry/vs-preview#67]
I've set DPI scaling to 200% at windows setting(Global).
![image](https://user-images.githubusercontent.com/21131439/210134917-a0d384b6-6d6c-4369-b04b-29d40e740303.png)
 I notice that the frame rendering at 200% too (the ui shows 100% scaling, but it spends 4x actual pixels). is it possible to keep it 100% size (pixel to pixel) even when I set the DPI to 200%

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/be2a8312d33ba360b9ad8704e1cb98a260763efb.
