### ISSUE TITLE
Scening importing v1 keyframes doesn't work

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#70]
When importing files for scening, you get the following menu, signifying there is support for v1 keyframes:

![image](https://user-images.githubusercontent.com/42927908/219747382-21989c0d-7f9d-4b22-8af1-28059cbd1b7b.png)

The keyframes were generated using the `vstools.Keyframes.to_file` method, which adds a v1 header to the file. File in question: [NegimaS2DVD_01_scening.txt](https://github.com/Irrational-Encoding-Wizardry/vs-preview/files/10769889/NegimaS2DVD_01_scening.txt)

When loading in, nothing appears to happen. However, the file works flawlessly when choosing `IfoEdit Celltimes`.

**Comment by Setsugennoao** [comment]
Was eventually fixed between this and vstools changes.
