### ISSUE TITLE
Add support for Slow.pics Tagging, TMDB Title link, and Account

### ISSUE THREAD

**Issue by Matt2011-8717** [Irrational-Encoding-Wizardry/vs-preview#73]
- Add support for Slow.pics tagging and TMDB link for greater organization.
- Add Account support so users can manage their comps

Relevant Image:
![image](https://user-images.githubusercontent.com/127539101/224381441-384b7339-3469-440d-bc6d-e10ccd493d2c.png)

**Comment by Matt2011-8717** [comment]
@Setsugennoao

**Comment by Aiwez** [comment]
forgot to mention, also add support for `Remove after N days:` in comper, since by default slow.pics sets it at 2 Years.

Relevant Image:
![image](https://user-images.githubusercontent.com/127626548/224507999-343b091e-241a-4af5-a09a-fe5e5c5f3fb2.png)

**Comment by Aiwez** [comment]
@Setsugennoao
