### ISSUE TITLE
Warn the user before deleting list

### ISSUE THREAD

**Issue by NSQY** [Irrational-Encoding-Wizardry/vs-preview#74]
Padre nostro che sei nei cieli,
sia santificato il tuo nome,
venga il tuo regno,
sia fatta la tua volontà
come in cielo così in terra.

Dacci oggi il nostro pane quotidiano,
e rimetti a noi i nostri debiti
come noi li rimettiamo ai nostri debitori,
e non ci indurre in tentazione,
ma liberaci dal male.

Amen.

**Comment by Matt2011-8717** [comment]
gówniany język jest niedozwolony

**Comment by Setsugennoao** [comment]
zamknij morde kurwa

**Comment by LightArrowsEXE** [comment]
Hij heeft een punt, weet je?
