### ISSUE TITLE
Add a hotkey to paste current frame into Manual Frame row

### ISSUE THREAD

**Issue by Matt2011-8717** [Irrational-Encoding-Wizardry/vs-preview#75]
It's quite tedious copying, pasting, putting a comma and a space for every frame I wanna add to my comp. A hotkey that takes the current frame and adds it to the manual list of frames would be amazing.
![image](https://user-images.githubusercontent.com/127539101/224382857-31903226-070f-4b9a-b9cd-3b4e74323730.png)

**Comment by Matt2011-8717** [comment]
@Setsugennoao

**Comment by NSQY** [comment]
https://discord.com/channels/856381934052704266/955234268643196998/1045447901192659046

**Comment by Setsugennoao** [comment]
Moved to #89
